/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPFSChat } from "./IPFSChat";
export * as factories from "./factories";
export { IPFSChat__factory } from "./factories/IPFSChat__factory";
